name: test
run-name: ${{ gitea.actor }} is building
on:
  push:
    branchs: [main]

jobs:
  test:
    runs-on: host

    steps:
      - uses: actions/checkout@v4
      - run: scripts/run-end-to-end-tests

  docs:
    needs: [test]
    runs-on: host
    env:
      IMAGE_NAME: projects.torsion.org/borgmatic-collective/borgmatic:docs

    steps:
      - uses: actions/checkout@v4
      - run: podman login --username "${{ secrets.REGISTRY_USERNAME }}" --password "${{ secrets.REGISTRY_PASSWORD }}" projects.torsion.org
      - run: podman build --tag "$IMAGE_NAME" --file docs/Dockerfile --storage-opt "overlay.mount_program=/usr/bin/fuse-overlayfs" .
      - run: podman push "$IMAGE_NAME"
