name: test
run-name: ${{ gitea.actor }} is running tests
on: [push]

jobs:
  test:
    runs-on: host

    steps:
      - uses: actions/checkout@v4
      - run: scripts/run-end-to-end-tests
      - run: find . -name borgmatic-1.8.9.dev0
